### ISSUE TITLE
can't find the repos mentioned in README

### ISSUE THREAD

**Issue by muddlebee** [fky2015/substrate-with-pBFT#4]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

below projects not reachable

git clone https://github.com/bit-substrate/finality-tendermint.git
git clone https://github.com/bit-substrate/finality-pbft.git
git clone https://github.com/bit-substrate/finality-jasmine.git
git clone https://github.com/bit-substrate/bit-substrate.git

**Comment by fky2015** [comment]
Sorry for the misleading information in the documents. I have updated them.
